<Project Sdk="Microsoft.NET.Sdk">
  <!-- Headless screenshots of the app. Usage in Program.cs. -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="12.1.3" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.3" />
    <ProjectReference Include="../../app/Dissonancia.App.csproj" />
  </ItemGroup>
</Project>
